name: Build Image and Push

on:
  push:

jobs:
  build:
    timeout-minutes: 60
    name: Build and push uptermd
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/flipstone/uptermd
          tags: |
            type=sha,format=short,prefix=
            type=raw,value={{commit_date 'YYYY-MM-DD'}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build, tag, and push image to GCR
        timeout-minutes: 60
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,mode=max,ignore-error=true
          cache-to: type=gha,mode=max,ignore-error=true
          platforms: 'linux/amd64'
